trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Dev
- name: my-passed-variable
   value:$[variablegroups.Dev.database1] # uses runtime expression
steps:
- script: echo $(database1) # uses macro syntax
- script: echo $(my-passed-variable) 

